### PR TITLE
allow configuration of installation dir

### PR DESCRIPTION
**Pull request by jmlucjav**
I install wsltty to another directory (for several reasons), this simple change allows it to do that easily

### CODE REVIEW

**Comment by mintty** [comment]
We can change the script but that won't affect the installation as there is no option to actually change the setting, so I see no purpose in this.
Also, my choice was to install next to WSL itself, which doesn't offer a choice either, so I think this is suitable.

**Comment by mintty** [comment]
> another directory (for several reasons)

which and for what reasons, actually?

**Comment by jmlucjav** [comment]
There is no option but the installation dir has only to be changed in one place, much easier thing to do than the current status.  Even if it was not to allow this, I believe this change makes the script cleaner, and being so so small I thought it would not be an issue to merge it.

My reason to install it in another place: I install it under dropbox, so it gets synced among all my hosts. The customizations I do in one gets replicated to others, works very well.

**Comment by jmlucjav** [comment]
appreciated!

**Pull request merged**
